// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Compiler is an autogenerated mock type for the Compiler type
type Compiler struct {
	mock.Mock
}

type Compiler_Expecter struct {
	mock *mock.Mock
}

func (_m *Compiler) EXPECT() *Compiler_Expecter {
	return &Compiler_Expecter{mock: &_m.Mock}
}

// Compile provides a mock function with given fields: ctx, reportPath, reportPDF, inputs
func (_m *Compiler) Compile(ctx context.Context, reportPath string, reportPDF string, inputs map[string]string) error {
	ret := _m.Called(ctx, reportPath, reportPDF, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Compile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) error); ok {
		r0 = rf(ctx, reportPath, reportPDF, inputs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Compiler_Compile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compile'
type Compiler_Compile_Call struct {
	*mock.Call
}

// Compile is a helper method to define mock.On call
//   - ctx context.Context
//   - reportPath string
//   - reportPDF string
//   - inputs map[string]string
func (_e *Compiler_Expecter) Compile(ctx interface{}, reportPath interface{}, reportPDF interface{}, inputs interface{}) *Compiler_Compile_Call {
	return &Compiler_Compile_Call{Call: _e.mock.On("Compile", ctx, reportPath, reportPDF, inputs)}
}

func (_c *Compiler_Compile_Call) Run(run func(ctx context.Context, reportPath string, reportPDF string, inputs map[string]string)) *Compiler_Compile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *Compiler_Compile_Call) Return(_a0 error) *Compiler_Compile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Compiler_Compile_Call) RunAndReturn(run func(context.Context, string, string, map[string]string) error) *Compiler_Compile_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, reportPath, reportPDF, inputs
func (_m *Compiler) Watch(ctx context.Context, reportPath string, reportPDF string, inputs map[string]string) error {
	ret := _m.Called(ctx, reportPath, reportPDF, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) error); ok {
		r0 = rf(ctx, reportPath, reportPDF, inputs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Compiler_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type Compiler_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - reportPath string
//   - reportPDF string
//   - inputs map[string]string
func (_e *Compiler_Expecter) Watch(ctx interface{}, reportPath interface{}, reportPDF interface{}, inputs interface{}) *Compiler_Watch_Call {
	return &Compiler_Watch_Call{Call: _e.mock.On("Watch", ctx, reportPath, reportPDF, inputs)}
}

func (_c *Compiler_Watch_Call) Run(run func(ctx context.Context, reportPath string, reportPDF string, inputs map[string]string)) *Compiler_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *Compiler_Watch_Call) Return(_a0 error) *Compiler_Watch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Compiler_Watch_Call) RunAndReturn(run func(context.Context, string, string, map[string]string) error) *Compiler_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// QueryVars provides a mock function with given fields: ctx, reportPath
func (_m *Compiler) QueryVars(ctx context.Context, reportPath string) (map[string]string, error) {
	ret := _m.Called(ctx, reportPath)

	if len(ret) == 0 {
		panic("no return value specified for QueryVars")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, reportPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, reportPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reportPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Compiler_QueryVars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryVars'
type Compiler_QueryVars_Call struct {
	*mock.Call
}

// QueryVars is a helper method to define mock.On call
//   - ctx context.Context
//   - reportPath string
func (_e *Compiler_Expecter) QueryVars(ctx interface{}, reportPath interface{}) *Compiler_QueryVars_Call {
	return &Compiler_QueryVars_Call{Call: _e.mock.On("QueryVars", ctx, reportPath)}
}

func (_c *Compiler_QueryVars_Call) Run(run func(ctx context.Context, reportPath string)) *Compiler_QueryVars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Compiler_QueryVars_Call) Return(_a0 map[string]string, _a1 error) *Compiler_QueryVars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Compiler_QueryVars_Call) RunAndReturn(run func(context.Context, string) (map[string]string, error)) *Compiler_QueryVars_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompiler creates a new instance of Compiler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompiler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Compiler {
	mock := &Compiler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
